### PR TITLE
CLI implementation

### PR DESCRIPTION
**Pull request by Tofull**
I created a simple CLI to use this amazing project as a script to process thousands tree pointclouds in a row. This allows to export the branches model `.obj` file.

## CLI description:
AdTree can now be run in two modes, which can be selected based on arguments:
- no arguments to open the GUI.

	Example:
        `AdTree`

- exactly two arguments to run the CLI.

    To use the CLI, AdTree expects : `./AdTree <xyz_file_path> <output_folder>`

    The `<output_folder>` will be created if it doesn't exist.

    Example:

    `AdTree "./data/tree1.xyz" "./export_branches_models"`

## Fixes:

- [x] fix issue about writing branches models in double-precision coordinates (this might have been fixed on more recent easy3d version, I don't know).
- [x] fix issue about .obj write operation when no normals are provided
- [x] fix small typos in README.md
- [x] implement a simple CLI

### CODE REVIEW

**Review by LiangliangNan — CHANGES_REQUESTED** [review]
C++17 is not supported on my mac Version 10.15, which is already new (though not the latest).
To support a wider range of OS versions, it could better to stay with C++11.
Most the std::file_system functionalities have already been implemented in
`third_party/easy3d/util/file_system.h`

**Review by LiangliangNan — COMMENTED** [review]
The whole project uses `float`, which seems sufficient.
Is there a particular reason for this `translation` uses `double`?
If not, it is better to switch back to `float` to avoid confusion and potential bugs (e.g., requesting `vec3` property returns a NULL translation property)

**Review by LiangliangNan — CHANGES_REQUESTED** [review]
Normal information in OBJ files is optional. All (seems to be) rendering software either compute the normals before or in rendering (taking advantage of the GPU power).
In fact (very special cases), wrong geometry + tuned normals give good rendering. But the rendering may not reflect the actual geometry of the model.
So I'd say we intended to ignore the normal information.

Besides,  in line 549, should `" %d"` be `" %d//%d"`  ?

**Comment by LiangliangNan** [comment]
@Tofull Thanks for the great contribution!!!
We had this plan to support multiple running modes, but never got time on it. This is cool.
I left some comments.

**Comment by Tofull** [comment]
> C++17 is not supported on my mac Version 10.15, which is already new (though not the latest).
> To support a wider range of OS versions, it could better to stay with C++11.
> Most the std::file_system functionalities have already been implemented in
> `third_party/easy3d/util/file_system.h`

I didn't find any `concat`-like function in `<easy3d/util/file_system.h>`. But as we can determine the `native_path_separator()`, I can just use it to concat the strings.

**Comment by Tofull** [comment]
> The whole project uses `float`, which seems sufficient.
> Is there a particular reason for this `translation` uses `double`?
> If not, it is better to switch back to `float` to avoid confusion and potential bugs (e.g., requesting `vec3` property returns a NULL translation property)

Well, I had troubles with pointclouds from Jakarto. Those are projected in a metric grid-based coordinate system ([EPSG:2950](https://epsg.io/2950)). The `Y` value exceeds the float precision.

Here is a sample from Jakarto : 
[download sample_jakarto.zip](https://github.com/tudelft3d/adtree/files/5926399/sample_jakarto.zip)


- `float__jakarto_tree_1_branches.obj` has been generated if `translation` uses `float`, with the prior version of AdTree.
- `double__jakarto_tree_1_branches.obj` has been generated if `translation` uses `double`, with normals removal fix.
- `tree_pointcloud/jakarto_tree_1.xyz` is the related pointcloud, for reference.

As you will see, the `.obj` are different. I can't open the float-generated `.obj` on CloudCompare; and succeed to open the double-generated one. The failure happens because of the normal information in .obj files : 
image

By the way, if you look at the vertices coordinates, you will see that the coordinates are rounded due to precision losses: 

```
$ head -5 double__jakarto_tree_1_branches.obj
# OBJ exported from Easy3D
v 278935.1227574522 5036389.8747296408 46.3677168028
v 278935.1389935786 5036389.8799835816 46.3669600623
v 278935.1490280802 5036389.8937804475 46.3660972254
v 278935.1490280802 5036389.9108503237 46.3654580252
--
```

```
$ head -5 float__jakarto_tree_1_branches.obj
# OBJ exported from Easy3D
v 278935.1250000000 5036390.0000000000 46.3677139282
v 278935.1562500000 5036390.0000000000 46.3669586182
v 278935.1562500000 5036390.0000000000 46.3660964966
v 278935.1562500000 5036390.0000000000 46.3654556274
--
```

**Comment by Tofull** [comment]
I added two more commits to reflect the changes request.

**Comment by LiangliangNan** [comment]
@Tofull  I merged your pull request, and also cleaned the code. Thanks!

**Comment by LiangliangNan** [comment]
@Tofull 
Just fixed a bug (where coordinates in the reconstructed model might be NaN).
Also, now it allows to take a directory as an argument and process all the xyz files in the directory).

**Comment by Tofull** [comment]
It works like a charm. Thank you @LiangliangNan.

**Pull request merged**
